### ISSUE TITLE
Trouble downloading the github package

### ISSUE THREAD

**Issue by SeabassWells** [govtrack/govtrack.us-web#155]
Hi. I tried to install the package with python 2.7 and python 3.6. I received this error message

```
pip install git+git://github.com/govtrack/govtrack.us-web.git
Collecting git+git://github.com/govtrack/govtrack.us-web.git
  Cloning git://github.com/govtrack/govtrack.us-web.git to /private/var/folders/ng/kd7qw6vj0c14gws66zf34vbr0000gn/T/pip-req-build-vh1mud2m
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/ng/kd7qw6vj0c14gws66zf34vbr0000gn/T/pip-req-build-vh1mud2m/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ng/kd7qw6vj0c14gws66zf34vbr0000gn/T/pip-req-build-vh1mud2m/
```

I installed `gitpython` before running this command. I'm trying to recreate the [sponsorship_analysis.py](https://www.govtrack.us/about/analysis#ideology) for the 115th congress.

**Comment by JoshData** [comment]
Hi,

GovTrack isn't installable using pip. There are step-by-step instructions in the project's README.

But there are a lot of moving pieces in GovTrack and to recreate just the analysis, you are probably better off fetching the source bill data directly (https://github.com/unitedstates/congress) and re-implementing the analysis from scratch using our source code as an example.
